### ISSUE TITLE
Chart Manager

### ISSUE THREAD

**Issue by Number11** [mariusso/XrmToolboxPlugins#2]
I have exported my personal charts and am trying to import them as system charts.  When I use the "Import Charts" feature I get an error message "Missing 'description' node".  Not sure what I'm doing wrong.

**Comment by Number11** [comment]
It appears that if the description section of a chart is blank, the section isn't created in the export file so the fix is to add a description in the chart designer.

**Comment by MscrmTools** [comment]
Why did you create an issue in this project that is not XrmToolBox project?

**Comment by mariusso** [comment]
Issues closed. XRMToolbox project is here: https://github.com/MscrmTools/XrmToolBox

**Comment by Number11** [comment]
Chart Manager is a product of XRM Toolbox

**Comment by MscrmTools** [comment]
Yes and this GitHub repository is not XrmToolBox one
